// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWpvGgOXkUfPcFhlDXAgCJ4RX3Z0dQ_AY',
    appId: '1:544675422784:web:48f323479882609eba75a5',
    messagingSenderId: '544675422784',
    projectId: 'doancuoiky-c8804',
    authDomain: 'doancuoiky-c8804.firebaseapp.com',
    storageBucket: 'doancuoiky-c8804.firebasestorage.app',
    measurementId: 'G-Z0FP6H46X5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrr4CJMYk7kTFsa0Dr3lUtzVEAqFc7tB8',
    appId: '1:544675422784:android:e57f2c019e452129ba75a5',
    messagingSenderId: '544675422784',
    projectId: 'doancuoiky-c8804',
    storageBucket: 'doancuoiky-c8804.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa1Eg11VyJAa3BgZokGS9EuXI_wuqI-Po',
    appId: '1:544675422784:ios:8b09e3115eae8969ba75a5',
    messagingSenderId: '544675422784',
    projectId: 'doancuoiky-c8804',
    storageBucket: 'doancuoiky-c8804.firebasestorage.app',
    iosBundleId: 'com.example.doanNganhang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa1Eg11VyJAa3BgZokGS9EuXI_wuqI-Po',
    appId: '1:544675422784:ios:8b09e3115eae8969ba75a5',
    messagingSenderId: '544675422784',
    projectId: 'doancuoiky-c8804',
    storageBucket: 'doancuoiky-c8804.firebasestorage.app',
    iosBundleId: 'com.example.doanNganhang',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWpvGgOXkUfPcFhlDXAgCJ4RX3Z0dQ_AY',
    appId: '1:544675422784:web:176b9a32249cab4bba75a5',
    messagingSenderId: '544675422784',
    projectId: 'doancuoiky-c8804',
    authDomain: 'doancuoiky-c8804.firebaseapp.com',
    storageBucket: 'doancuoiky-c8804.firebasestorage.app',
    measurementId: 'G-5HBFP9EDCN',
  );
}
