class MockInvoice {
  const MockInvoice({
    required this.code,
    required this.serviceType,
    required this.aliasVi,
    required this.aliasEn,
    required this.customerName,
    required this.serviceAddress,
    required this.billingPeriodText,
    required this.dueDateIso,
    required this.amountVnd,
    this.usageValue = 0,
    this.usageUnit = '',
    this.provider = '',
  });

  final String code;
  final String serviceType;
  final String aliasVi;
  final String aliasEn;
  final String customerName;
  final String serviceAddress;
  final String billingPeriodText;
  final String dueDateIso;
  final int amountVnd;
  final double usageValue;
  final String usageUnit;
  final String provider;
}

final Map<String, MockInvoice> mockInvoices = <String, MockInvoice>{
  'PE13000456281': const MockInvoice(
    code: 'PE13000456281',
    serviceType: 'electric',
    aliasVi: 'Nhà riêng',
    aliasEn: 'Home',
    customerName: 'NGUYEN VAN AN',
    serviceAddress: '123 Duong Lang, Ha Noi',
    billingPeriodText: '03/2026',
    dueDateIso: '2026-04-10',
    amountVnd: 854000,
    usageValue: 365,
    usageUnit: 'kWh',
    provider: 'EVN',
  ),
  'PE13000998724': const MockInvoice(
    code: 'PE13000998724',
    serviceType: 'electric',
    aliasVi: 'Văn phòng',
    aliasEn: 'Office',
    customerName: 'CONG TY AN PHAT',
    serviceAddress: '18 Le Van Luong, Ha Noi',
    billingPeriodText: '03/2026',
    dueDateIso: '2026-04-12',
    amountVnd: 3450000,
    usageValue: 512,
    usageUnit: 'kWh',
    provider: 'EVN',
  ),
  'WA88000123456': const MockInvoice(
    code: 'WA88000123456',
    serviceType: 'water',
    aliasVi: 'Nhà riêng',
    aliasEn: 'Home',
    customerName: 'NGUYEN THI MAI',
    serviceAddress: '288 Le Loi, Quan 1, TP.HCM',
    billingPeriodText: '03/2026',
    dueDateIso: '2026-04-11',
    amountVnd: 145000,
    usageValue: 18,
    usageUnit: 'm3',
    provider: 'SAWACO',
  ),
  'WA88000654321': const MockInvoice(
    code: 'WA88000654321',
    serviceType: 'water',
    aliasVi: 'Phòng trọ',
    aliasEn: 'Rental room',
    customerName: 'TRAN QUANG VINH',
    serviceAddress: 'A12 Sky Garden, Quan 7, TP.HCM',
    billingPeriodText: '03/2026',
    dueDateIso: '2026-04-13',
    amountVnd: 72000,
    usageValue: 9,
    usageUnit: 'm3',
    provider: 'SAWACO',
  ),
  'INFPT223344': const MockInvoice(
    code: 'INFPT223344',
    serviceType: 'internet',
    aliasVi: 'FPT Telecom',
    aliasEn: 'FPT Telecom',
    customerName: 'LE MINH KHANG',
    serviceAddress: '78 Nguyen Thi Minh Khai, TP.HCM',
    billingPeriodText: '03/2026',
    dueDateIso: '2026-04-15',
    amountVnd: 255000,
    usageValue: 300,
    usageUnit: 'Mbps',
    provider: 'FPT',
  ),
  'INVNPT998877': const MockInvoice(
    code: 'INVNPT998877',
    serviceType: 'internet',
    aliasVi: 'VNPT',
    aliasEn: 'VNPT',
    customerName: 'HOANG LINH CHI',
    serviceAddress: '25 Tran Hung Dao, Ha Noi',
    billingPeriodText: '03/2026',
    dueDateIso: '2026-04-17',
    amountVnd: 880000,
    usageValue: 1000,
    usageUnit: 'Mbps',
    provider: 'VNPT',
  ),
  'INVT225588': const MockInvoice(
    code: 'INVT225588',
    serviceType: 'internet',
    aliasVi: 'Viettel',
    aliasEn: 'Viettel',
    customerName: 'DO DUC TRUNG',
    serviceAddress: '63 Cach Mang Thang 8, Da Nang',
    billingPeriodText: '03/2026',
    dueDateIso: '2026-04-18',
    amountVnd: 220000,
    usageValue: 250,
    usageUnit: 'Mbps',
    provider: 'Viettel',
  ),
  'MO0901234567': const MockInvoice(
    code: 'MO0901234567',
    serviceType: 'mobile_postpaid',
    aliasVi: 'Mobifone',
    aliasEn: 'Mobifone',
    customerName: 'PHAM NGOC TUAN',
    serviceAddress: 'Thanh toán cước trả sau',
    billingPeriodText: '03/2026',
    dueDateIso: '2026-04-20',
    amountVnd: 199000,
    usageValue: 1,
    usageUnit: 'month',
    provider: 'Mobifone',
  ),
  'MO0332211445': const MockInvoice(
    code: 'MO0332211445',
    serviceType: 'mobile_postpaid',
    aliasVi: 'Viettel Pay',
    aliasEn: 'Viettel Pay',
    customerName: 'NGUYEN THU HA',
    serviceAddress: 'Thanh toán cước trả sau',
    billingPeriodText: '03/2026',
    dueDateIso: '2026-04-20',
    amountVnd: 500000,
    usageValue: 1,
    usageUnit: 'month',
    provider: 'Viettel',
  ),
};
